# Generated by Django 3.2.7 on 2021-09-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('craetion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
