# Generated by Django 3.2.7 on 2021-09-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tododata',
            old_name='craetion',
            new_name='creation',
        ),
    ]
