# Generated by Django 3.2.7 on 2021-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_craetion_tododata_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododata',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
